### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by nuest** [richfitz/modeladequacy#104]
Hi! Interesting approach and some cool packages!

I just tried to remake the analysis, after sorting out several missing dependencies and packages that could not automatically be installed, remake stops with this error:

> cannot open URL 'http://www.leda-traitbase.org/LEDAportal/objects/Data_files/SLA%20und%20geo.txt': HTTP status was '404 Not Found

Any idea how to fix that?

**Comment by nuest** [comment]
I actually had contact with the current maintainer of the database a little while ago. I pointed this issue out to him and he told me that the following URL should still work today, because the domain is not in use anymore:

http://www.uni-oldenburg.de/fileadmin/user_upload/biologie/ag/landeco/download/LEDA/Data_files/SLA_und_geo.txt

**Comment by wcornwell** [comment]
thanks for this!  new url works for me

**Comment by wcornwell** [comment]
Hopefully that fixes it...it's interesting to see what breaks over time with these reproducible workflows...

**Comment by richfitz** [comment]
https://www.w3.org/Provider/Style/URI.html

![](http://i.giphy.com/33iqmp5ATXT5m.gif)
